### PR TITLE
DSND-2433: Transform RES15s

### PR DESCRIPTION
**Pull request by cgregoryCH**
## Describe the changes
* Implements handling of RES15 form types.
* Also handles cases where description values may be persisted as empty.

### Related Jira tickets
[DSND-2433](https://companieshouse.atlassian.net/browse/DSND-2433)

### General
- [ ] Is the PR as small as it can be?
- [ ] Has the Jira ticket been updated with any relevant comments?
- [ ] Is the `README` up to date?
- [ ] Has the `POM` been updated for the latest versions of dependencies?
- [ ] Has the code been double-checked against `main`?
- [ ] Does the code adhere standards in this repository, including SonarQube checks?

### Testing
- [ ] Do the code changes have unit and integration tests with code coverage > 80%?
- [ ] Has the code been tested locally and/or passed the API Karate tests on Tilt?
- [ ] Have mandatory manual test cases been run?
- [ ] Are extra Karate tests required?
- [ ] Are all the test data resources up to date?

### Release preparation
_Where possible, add links to the respective Jira tickets when an item is checked_
- [ ] Have these changes been included in a release ticket?
- [ ] Are changes required to the `docker-chs-development` deployment or test data?
- [ ] Are any changes required to the environment added to `chs-configs`?

## Notes to the tester
_Add any testing hints or instructions here._

[DSND-2433]: https://companieshouse.atlassian.net/browse/DSND-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by johncook-ch — APPROVED** [review]

**Review by johncook-ch — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by johncook-ch — APPROVED** [review]
Have you thought about moving these calls to a helper class? Just a thought so please ignore if you want.
```
testConsumerAspect.resetLatch();
testConsumer.poll(Duration.ofMillis(Integer.getInteger("kafka.polling_duration", 1000)));
```

**Review by sthompsonCH — APPROVED** [review]

**Comment by cgregoryCH** [comment]
> Have you thought about moving these calls to a helper class? Just a thought so please ignore if you want.
> 
> ```
> testConsumerAspect.resetLatch();
> testConsumer.poll(Duration.ofMillis(Integer.getInteger("kafka.polling_duration", 1000)));
> ```

I'd like to do a full refactor of the tests once we've got all the ones we want to run on the pipeline, will add this in then.

**Pull request merged**
